url: "https://www.awakeningstudios.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: Nathan Selikoff, Interactive Experience Developer # the name of your site, e.g. ACME Corp.
description: I help design teams bring interactive experiences to life across exhibit & retail, data viz & web, live performance, and generative art. With over 20 years in production environments, my creative coding specialties include cross-platform 2D/3D graphics programming; parameterized design systems; gesture, multi-touch, motion and sensors; interactive data visualization; and real-time geospatial data pipelines.
author: Nathan Selikoff
twitter:
  username: nselikoff
  card: summary
logo: /assets/img/nathan-headshot-yellow-blue-480w.png
social:
  name: Ben Balter
  links:
    - https://twitter.com/nselikoff
    - https://www.linkedin.com/in/nathanselikoff/
    - https://github.com/nselikoff

plugins:
  - jekyll-postcss
  - jekyll-purgecss
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
    values:
      image:
        path: /assets/img/nathan-headshot-yellow-blue-480w.png
        width: 480
        height: 480

collections:
  projects:
    output: true
    permalink: /:collection/:name
    order: # also need to keep this in category order
      - why-war-video-wall.md
      - sfmoma-kiosk.md
      - t-mobile-video-wall.md
      - omnimodal-dashboard.md
      - asia-society-data-viz.md
      - thousand-faces-of-form-live-visuals.md
      - four-dimensions-live-visuals.md
      - new-music-miami-live-visuals.md
      - discovery-place-interactive-installation.md
      - anne-spalter-visual-effects-plugins.md
      - beautiful-chaos-leap-motion.md
